SELECT * FROM CATEGORY_TABLE
---insert into admin table
INSERT INTO ADMIN_TABLE (EMAIL, PASS) VALUES ('joyboy@yahoo.com', '00000020');
INSERT INTO ADMIN_TABLE (EMAIL, PASS) VALUES ('luffy@yahoo.com', '2134556');
INSERT INTO ADMIN_TABLE (EMAIL, PASS) VALUES ('nami@yahoo.com', '765432');
INSERT INTO ADMIN_TABLE (EMAIL, PASS) VALUES ('jhayabayon18@gmail.com', '0000010');
SELECT * FROM ADMIN_TABLE
---insert into category table
INSERT INTO CATEGORY_TABLE (CATEGORY_NAME) VALUES ('APPLIANCES');
INSERT INTO CATEGORY_TABLE (CATEGORY_NAME) VALUES ('External');
INSERT INTO CATEGORY_TABLE (CATEGORY_NAME) VALUES ('Internal');
INSERT INTO CATEGORY_TABLE (CATEGORY_NAME) VALUES ('Peripherals');
SELECT * FROM CATEGORY_TABLE
---insert into product table
INSERT INTO PRODUCT_TABLE (PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY) 
VALUES ('Keyboard','U00004','500.00', 'Keyboard.jpg', '10');
INSERT INTO PRODUCT_TABLE (PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY) 
VALUES ('Mouse','U00005','200.00', 'mouse.jpg', '5');
INSERT INTO PRODUCT_TABLE (PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY) 
VALUES ('Monitor','U00003','70000.00', 'monitor.jpg', '20');
INSERT INTO PRODUCT_TABLE (PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY) 
VALUES ('Washing Machine','U00004','90000.00', 'washing machine.jpg', '20');
INSERT INTO PRODUCT_TABLE (PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY) 
VALUES ('Washing Machine','U00004','90000.00', 'washing machine.jpg', '20');
INSERT INTO PRODUCT_TABLE (PRODUCT_NAME, CATEGORY_ID, PRODUCT_PRICE, PRODUCT_IMAGE, PRODUCT_AVAILABLE_QTY) 
VALUES ('Washing Machine','U00004','90000.00', 'washing machine.jpg', '20');
SELECT * FROM PRODUCT_TABLE






